### ISSUE TITLE
For transparency, add section to wiki about how data is cleaned

### ISSUE THREAD

**Issue by sowdm** [openpolicedata/openpolicedata#109]
Describe process of data standardization including how columns are identified and how their data is standardized (i.e. which raw values are assigned which final standardized values). This is necessary for release of code that allows for data cleaning

**Comment by potto216** [comment]
@sowdm what are your thoughts on the following? The plan is to add a section on the wiki homepage about the reasoning for our data is cleaning process described in 
https://github.com/openpolicedata/opd-data/blob/main/CONTRIBUTING.MD#adding-a-dataset-to-openpolicedata. This will be written for an audience who want to know the why instead of the how and does not assume the audience is a developer.

**Comment by potto216** [comment]
After discussion we decided to close this issue and possibly create a new issue later to add this documentation to the website.
