### ISSUE TITLE
Review and make corrections/edits to standardization documentation

### ISSUE THREAD

**Issue by sowdm** [openpolicedata/openpolicedata#232]
See these 2 pages:
- https://openpolicedata.readthedocs.io/en/latest/getting_started/index.html#Data-Standardization
- https://openpolicedata.readthedocs.io/en/latest/examples/opd-examples/standardization.html

**Comment by potto216** [comment]
@sowdm great documentation that is clear. I saw one typo of "signal" instead of "single" in https://openpolicedata.readthedocs.io/en/latest/examples/opd-examples/standardization.html "signal subject / officer per row case."

I assume examples for aggressive concatenation such as "agg_race_cat" will be kept up to date in the documentation to show what columns are being combined.

**Comment by sowdm** [comment]
Typo corrected.

Agreed that the documentation should be kept up to date with regard to agg_race_cat

**Comment by potto216** [comment]
Great, closing this issue.
