### ISSUE TITLE
Failing to Install Dependency Packages

### ISSUE THREAD

**Issue by imrnmzri** [openpolicedata/openpolicedata#272]
Hi there,

I'm a first time contributor and would be happy to contribute in documentation for this project. I'm also a beginner in Python and git and would love to gain insights as to why this issue is happening on my environment. I am running this project in Windows using conda version 24.1.2.

In the [Contributors Guide](https://github.com/openpolicedata/openpolicedata/blob/main/CONTRIBUTING.MD#contributors-guide), the guide lists the codes to install dependencies as:

`conda install --file dev/requirements-conda.txt --file dev/requirements-test.txt` and 
`pip install -r dev/requirements-pip.txt`.

However, in dev/requirements-conda.txt, there is a line that was added in https://github.com/openpolicedata/openpolicedata/commit/0fafd95717338d26271737f288d5b369902f6576, and I received an error that says:

`CondaValueError: could not parse '-r ../requirements.txt' in: dev/requirements-test.txt`

Only when I remove this specific line is when I can successfully run the conda install line. I would like to learn on the reason why this line is added and how can I solve this error without removing the line.

Additionally, requirements-pip.txt does not exists in the dev file, so I am unable to run this line, with the error:

`ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'dev/requirements-pip.txt'`

With all of this, as I am running the Getting Started notebook in jupyter under the devel environment, I am still being asked to install basic packages such as pandas, and I do not see them available in these requirement textfiles as part of the dependency packages in the devel environment.

I am happy to be guided to the right path to solve this issue, and feel free to ask clarifying questions about my local environment.

Thanks so much!

**Comment by sowdm** [comment]
Hi @imrnmzri, 

First of all, thanks for your interest in contributing! 

Apologies for the error. Our Contributing Guide is a little out of date. I was actually about halfway through updating it (#206). I will push out the update today or tomorrow.

You did find an error in the Contributing Guide. We updated our requirements files a while back as you noted. We wanted the requirements file for a user to run the code to be in the top-level directory while the ones for Python developers to be in /dev. The `-r ../requirements.txt` points to another requirements file in the top-level directory. Conda appears to not be capable of parsing `-r ../requirements.txt` but pip is.  The top-level directory requirements file has the pandas install so that didn't get installed because of the error.

The instructions should now be:

```
conda install --file dev/requirements-conda.txt
pip install -r .\dev\requirements-test.txt  
```

**Comment by sowdm** [comment]
If you're interested in helping with the documentation, it is located in /docs. We use [Sphinx](https://www.sphinx-doc.org/en/master/) and [Read The Docs](https://readthedocs.org/). 

We have a [requirements file in /docs](https://github.com/openpolicedata/openpolicedata/blob/main/docs/requirements.yml) specific to the documentation. You may want to install that instead of the ones that you were installing which are more for Python development and testing (or you can install both in separate environments). To install the docs requirements, run:

`conda env create -f .\docs\requirements.yml`

This will create a conda environment called `opd-docs` which is specified in the yml file.

All of this will be in the new Contributing Guide which will be out shortly. I will be sure to notify when it is available.

Let us know if you need any further help setting up or if there is an issue that you want to tackle and need help getting started on. We're definitely happy to help as needed.

**Comment by imrnmzri** [comment]
Thanks @sowdm! This is helpful and I'm able to run the "Getting Started" document in docs with the dependencies using your suggestion
