### ISSUE TITLE
New Jersey Use of Force Download Button produces a different download link each time

### ISSUE THREAD

**Issue by sowdm** [openpolicedata/openpolicedata#80]
Can test by click download multiple times here: https://njoag.app.box.com/s/upgf6yyi9g0fyjg6ednhqmr69dg9crfh/file/943802348612

**Comment by sowdm** [comment]
Tucson data does too: https://policeanalysis.tucsonaz.gov/pages/traffic-enforcement

**Comment by sowdm** [comment]
Durham data may fall into the same category. The download link that is generated is temporary. 

https://live-durhamnc.opendata.arcgis.com/search?q=police

**Comment by sowdm** [comment]
St. Louis County Use of Force data has same temporary link issue as above: https://data.stlouisco.com/search?tags=HubPSData

**Comment by potto216** [comment]
The New Jersey Use of Force which can be accessed by selecting the "Download Full Dataset" at www.njoag.gov/force/ uses [box](https://www.box.com/) for their provider software. Because the data URL changes over time and doesn't directly point to the file the only two options I can find for accessing the data is to use:
1. Use a tool like [Selenium](https://www.selenium.dev/) to navigate with the GUI
2. Use [box's developer API] (https://developer.box.com/) to access the file.

Option 2 fits our software architecture. I used the  [Get file information function](https://developer.box.com/reference/get-files-id/) which returns the "download_url": "" in the JSON output. I tried to to use the file id for the NJOAG use of force XLSX file and received:
```
curl -i -X GET "https://api.box.com/2.0/files/109218320434663"
HTTP/2 401
date: Mon, 02 Jan 2023 18:21:37 GMT
strict-transport-security: max-age=31536000
www-authenticate: Bearer realm="Service", error="invalid_request", error_description="The access token was not found."
box-request-id: 02388a14f74b6db8ba49dff61485f9e35
x-envoy-upstream-service-time: 3
via: 1.1 google
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
```
I tried a few other iterations, but it appears an access token is needed. I'll contact njoag.gov to see what our options are for getting an access token.

**Comment by potto216** [comment]
Contacted njoag.gov to see what our options are for getting an access token and kept being referred to vendor. Closing issue because no practical way for users to get access tokens.
